spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ss_indiapay
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
